### ISSUE TITLE
Add Discord notify github action

### ISSUE THREAD

**Issue by pmdaly** [flashbots/mev-inspect-py#40]
PR's are flying in, would be helpfull to add a notification in the channel when there's a push to main.  Below is an example that works with slack.  

```
   - name: Slack Notify Flashbots
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_ICON: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSq27uOJCFTdMUJ1hzetFjERg9e1iD5OrkPfg&usqp=CAU
        SLACK_COLOR: '#22b7f2'
        SLACK_CHANNEL: mev-inspect
        SLACK_USERNAME: mergbot
        SLACK_FOOTER: 'remember to merge!'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DBS }}
```

Here's a basic discord action
https://github.com/marketplace/actions/actions-for-discord

Another with more options
https://github.com/marketplace/actions/fancier-discord-webhooks
